# Generated by Django 5.2.11 on 2026-02-26 12:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Personagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("nivel", models.PositiveIntegerField(default=1)),
                ("experiencia", models.BigIntegerField(default=0)),
                (
                    "dinheiro",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "energia",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("esta_ocupado", models.BooleanField(default=False)),
                (
                    "tarefa_atual",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_conclusao_tarefa", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personagem",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personagens",
            },
        ),
    ]
