# Generated by Django 5.2.11 on 2026-02-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("posicao_x", models.IntegerField(default=0)),
                ("posicao_y", models.IntegerField(default=0)),
                ("descricao", models.TextField(blank=True)),
                (
                    "imagem_mapa",
                    models.CharField(default="icon-default.png", max_length=100),
                ),
            ],
            options={
                "verbose_name_plural": "Locais",
            },
        ),
        migrations.AddField(
            model_name="personagem",
            name="posicao_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personagem",
            name="posicao_y",
            field=models.IntegerField(default=0),
        ),
    ]
