# Generated by Django 5.2.11 on 2026-02-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogo", "0002_local_personagem_posicao_x_personagem_posicao_y"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "valor_venda",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FERRAMENTA", "Ferramenta"),
                            ("RECURSO", "Recurso"),
                            ("EQUIPAMENTO", "Equipamento"),
                        ],
                        default="RECURSO",
                        max_length=20,
                    ),
                ),
                (
                    "imagem_icon",
                    models.CharField(default="item-default.png", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "personagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mochila",
                        to="jogo.personagem",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jogo.item"
                    ),
                ),
            ],
        ),
    ]
